version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq  # ← Adicione esta linha
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf  # ← Adicione esta linha
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # ← Adicione este mapeamento